version: 1.1.{build}
image: Visual Studio 2017 Preview
build_script:
- cmd: >-
    nuget restore
    
    msbuild /m /p:Configuration=Release /clp:v=m MSBuildStructuredLog.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: msbuild.binlog
  name: MSBuild Log
on_failure:
- appveyor PushArtifact msbuild.binlog
