version: 1.1.{build}
image: Visual Studio 2017
install:
  - choco upgrade chocolatey # Need at least 0.10.8 to avoid packaging error
build_script: 
- cmd: >-
    nuget restore
    
    msbuild /m /p:Configuration=Release /clp:v=m MSBuildStructuredLog.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: msbuild.binlog
  name: MSBuild Log
- path: 'bin\**\msbuild-structured-log-viewer*.nupkg'
  name: Chocolatey Package

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/<UNIQUE_ORG_ID_FOR_MSBuildStructuredLog>/Integrations/AppVeyor?ProjectKey=MSBuildStructuredLog&SigningPolicyKey=release-signing
    authorization:
      secure: <SECURE_TOKEN_STORED_IN_APPVEYOR>