version: 1.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017 Preview
configuration: Release
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
test: off